// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using squares_api_excercise.Data;

#nullable disable

namespace squares_api_excercise.Migrations
{
    [DbContext(typeof(SquaresDbContext))]
    partial class SquaresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("squares_api_excercise.Models.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("squares_api_excercise.Models.Square", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("P1Id")
                        .HasColumnType("int");

                    b.Property<int>("P2Id")
                        .HasColumnType("int");

                    b.Property<int>("P3Id")
                        .HasColumnType("int");

                    b.Property<int>("P4Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("P1Id");

                    b.HasIndex("P2Id");

                    b.HasIndex("P3Id");

                    b.HasIndex("P4Id");

                    b.ToTable("Squares");
                });

            modelBuilder.Entity("squares_api_excercise.Models.Square", b =>
                {
                    b.HasOne("squares_api_excercise.Models.Point", "P1")
                        .WithMany()
                        .HasForeignKey("P1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("squares_api_excercise.Models.Point", "P2")
                        .WithMany()
                        .HasForeignKey("P2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("squares_api_excercise.Models.Point", "P3")
                        .WithMany()
                        .HasForeignKey("P3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("squares_api_excercise.Models.Point", "P4")
                        .WithMany()
                        .HasForeignKey("P4Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("P1");

                    b.Navigation("P2");

                    b.Navigation("P3");

                    b.Navigation("P4");
                });
#pragma warning restore 612, 618
        }
    }
}
